CREATE TABLE folder_history (
 id VARCHAR(36) PRIMARY KEY,
 sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
 folder_id VARCHAR(80) NOT NULL REFERENCES workspace_folders(id) ON DELETE CASCADE,
 entity_type VARCHAR(20) NOT NULL,
 entity_id VARCHAR(80) NOT NULL,
 entity_revision INT NOT NULL,
 action VARCHAR(40) NOT NULL,
 actor_id VARCHAR(100) NOT NULL,
 actor_name VARCHAR(200) NOT NULL,
 before_state TEXT NOT NULL,
 after_state TEXT NOT NULL,
 created_at BIGINT NOT NULL
);
CREATE INDEX folder_history_folder ON folder_history(folder_id,sequence);
CREATE INDEX folder_history_entity ON folder_history(entity_type,entity_id,sequence);
ALTER TABLE folder_entry_versions ADD COLUMN folder_id VARCHAR(80);
UPDATE folder_entry_versions SET folder_id=(SELECT e.folder_id FROM folder_entries e WHERE e.id=folder_entry_versions.entry_id);
ALTER TABLE folder_entry_versions ALTER COLUMN folder_id SET NOT NULL;
